# JWT Configuration
examly.app.jwtSecret=examlySecretKey
examly.app.jwtExpirationMs=86400000

# Swagger Configuration
enable.swagger.plugin=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

# Active profile (change as needed)
spring.profiles.active=dev